### ISSUE TITLE
Allow merge of new manifest in old manifest

### ISSUE THREAD

**Issue by ryuran** [aribouius/webpack-plugin-manifest#1]
I use same json for js and css manifest.
But the latest erase the first one.

**Comment by aribouius** [comment]
I'm afraid I don't follow.  Can you please elaborate on your issue.

**Comment by ryuran** [comment]
Yes, I can.
I use webpack-plugin-manifest for javascript build with webpack.
I use gulp-rev for javascript build with gulp.

But webpack-plugin-manifest erase old json file instead of merge new entries inside.

**Comment by aribouius** [comment]
@ryuran apologies for the delay.  I have [added](https://github.com/aribouius/webpack-plugin-manifest/commit/fe2be963e6e3870228a2f7f1fd634e1cff22f205) a new `merge` configuration option which you can use to indicate that an existing manifest file should get merged.
